apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: dev-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "www.webserver.com"
      port:
        name: http
        number: 80
        protocol: HTTP
    